
String light_box_html = 
  "<html><head>\n"
  "  <link rel='stylesheet' href='https://www.w3schools.com/w3css/4/w3.css'>\n"
  "  <title>Light Box</title> \n"
  "</head>\n"
  "<style> input { width: 80%; } </style>\n"
  "<body>\n"
  "<div class='w3-container'><h1>Welcome to Light Box</h1></div \n"
  "<form id='color_form' name='color_form' method='post' action='/mode' class='w3-container w3-border w3-margin'> \n"
  "  <table class='w3-table'>\n"
  "    <tr><td colspan='2'><h><center>Front</center></h></td> <td colspan='2'><h><center>Back</center></h> </td>\n"
  "    <tr><td class='w3-right-align'>Red</td><td> <input type='range' min='0' max='200' value='50' id='red' name='f_red'></td>\n"
  "        <td class='w3-right-align'>Red</td><td> <input type='range' min='0' max='200' value='50' id='red' name='b_red'></td></tr>\n"
  "    <tr><td class='w3-right-align'>Green</td><td> <input type='range' min='0' max='200' value='50' id='green' name='f_green'></td>\n"
  "        <td class='w3-right-align'>Green</td><td> <input type='range' min='0' max='200' value='50' id='green' name='b_green'></td></tr>\n" 
  "    <tr><td class='w3-right-align'>Blue</td><td> <input type='range' min='0' max='200' value='50' id='blue' name='f_blue'></td>\n"
  "        <td class='w3-right-align'>Blue</td><td> <input type='range' min='0' max='200' value='50' id='blue' name='b_blue'></td></tr>\n"
  "    <tr><td colspan='4'><center><input type='submit' value='update' class='w3-button w3-gray w3-round-xlarge w3-round-xlarge' style='width:120px' ></td></tr> \n"
  "  </table>\n"
  "</form>"
  "<script> \n"
  "  function formSubmit(event) { \n"
  "    event.preventDefault(); // Stop normal submission\n"
  "    \n"
  "    var url = '/json'; \n"
  "    var request = new XMLHttpRequest(); \n"
  "    request.open('POST', url, true); \n"
  "    request.setRequestHeader('Content-Type', 'application/json;charset=UTF-8'); \n"
  "    \n"
  "    let form_data = new FormData(event.target); \n"
  "    let form_obj = Object.fromEntries(form_data.entries()); \n"
  "    let front_data = {'red':parseInt(form_obj['f_red'], 10), \n"
  "                      'green':parseInt(form_obj['f_green'], 10), \n"
  "                      'blue':parseInt(form_obj['f_blue'], 10)}; \n"
  "    let back_data = {'red':parseInt(form_obj['b_red'], 10), \n"
  "                      'green':parseInt(form_obj['b_green'], 10), \n"
  "                      'blue':parseInt(form_obj['b_blue'], 10)}; \n"
  "    let data = {'front_data': front_data, 'back_data':back_data}; \n"

  "    const data_text = JSON.stringify(data, null, 2); \n"
  "    console.log(data_text); \n"
  "    request.send(data_text); \n"
  "  } \n"
  "  document.getElementById('color_form').addEventListener('submit', formSubmit); \n"
  "</script> \n";